language: java
jdk:
- oraclejdk8
os:
- linux
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
notifications:
  slack:
    secure: qpNqczXw6sfYKOTABJwBicrRoJEi4Fzh7qet2j0WtnlnD03VOymkTTS/M1tooEq+sOXPRuMdQmQkiZiHzButHOI37Ofgd2j2J2UtIdjq0IRBiOytBvyrM+IIbXIBX0pqvv/T1DnMv8TlT7A/vZYx+YJQLBdRID44IWrR3E2n8s1aTr6Nq+cNaVCyuX+mlgco3VJ1i93J9/9P/dI0J0Di4qmBmG3UxSSOrXrgpsqQYk/3A6OGr/m8Au8NYmOWI6Vd9kx7pe+nBCKr/ybYwIcpMcDJDP+KO4BPvFEzoAEs9+qctwMVRTh65hbhf9XBjEzPU5Zi7ygvtsxKCLCMz9+sX6VcSCejPb8ALVjNUre3Ksuaqn2wI7cZL109y/ly3PA2ta9WVfZ8q+e4hldlvcCH3UynS3ZcIQJTI8w+/cBaJMkW5LU3nEkSBJ+WoixZnryWF41IwBVK1E6qBtAAuiqmgxvbSwpP35oBX3ejU57ixVhN/E+j/B/wJJpfRMoL2eYpKHEgIOzg4TCRF8thUXS7vDGLAfy1nsZgRQ7N0QqNSkCXjWjp1kvr0Is3CyxfH/yOAa8sAFYI+b7E32Zl3rSY55NLPzHirkqxkor4jQwDDZ+IJagEHII8SsXfeLohNWIiyr5wYDqMHplbnHKP/y5b0OjZW5EPeeVgnrEoc+DfVoY=
before_deploy:
  - gradle fatjar
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: uXIyIhi/r17xPu5y7IyMHqUWEw44Cyl70JI9vStiFFRrKHE3DUJ6gENeIfEXwef9UHksGm85NKmwNiBj6aFk+0kMUc0YkvFBbqkJlGByEY/cAJaow/PK3W9jDp/PvnQLVxr+LbJDFys146iIiiLN+1dfHJrQDgA9IXWTnW+XdhifskG2URNu86LlJkUFWeOYplnCnqqLewHhRiO0B0ziDNZyilBwwO0jXRI9xG17hW+wyTi41y4w0LS0BxaL9+N2fyjZrWiSXbOqZerC3RvuG8pasW/Db+vvMfOxtwNY6F9iCzGO5PqSQgucgMwh+f0Q7TV8qDAADF9Y4y941+5byaz9eHcIoe5+0crVU+4dsZq0EOfznv45Srnf1aq/hHTyS6VwuLoe+ztqx4udxa7zE9N718iVPI1fXlYESbjYxQISKscvLQHdJoKFznjaKsD11U4mkPJemDgpBVlj01jIsfyu/4NJco16Ax48sgAvd0R+vHpBmhMOEP9eJ58F3VckvxltuJMUvNddsrU2VGGA4teLH/G9Gmr8QIps4kQQZwz3AqLTK2lSAHHxaXOW3ZrEGeAanJ8e3rCVKJThR4ca8PMPrO/81Xh+18Z+ilY89BNdvS42+ObyDxBU0COlEHs4k5t8+atdRV7t+O2BKoUfA6RbsjWDhpYwjxZrxcBDD10=
  file: "build/libs/DataExporter-all-*.jar"
  on:
    repo: MD2Korg/DataExporter
    tags: true
  skip_cleanup: true

